CREATE_TABLES = """
CREATE TABLE IF NOT EXISTS devices (
    id BIGSERIAL PRIMARY KEY,

    device_uuid UUID NOT NULL UNIQUE,

    hostname TEXT NOT NULL,

    serial_number TEXT,

    os_name TEXT,
    os_version TEXT,
    os_build TEXT,

    cpu TEXT,
    ram_bytes BIGINT,
    gpu TEXT,

    network_interfaces JSONB NOT NULL DEFAULT '[]'::jsonb,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    username TEXT NOT NULL UNIQUE,

    password_hash TEXT NOT NULL,

    is_admin BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS jwt_blocklist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    jti TEXT NOT NULL UNIQUE,

    expires_at TIMESTAMPTZ NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
"""